### ISSUE TITLE
Create a splode shell

### ISSUE THREAD

**Issue by oubiwann** [oxur/mdsplode#10]
Requirements:
* [x] Long-running, awaits input on `stdin`
* [x] Shell must be stateful
* [x] Supports the following commands:
  * [x] `read md <filename or data>`
    * [x] parses file or string data and sets/replaces state with results
    * [ ] writes `"{\"ok\": true}"` or `"{\"errors\": [ ...]}"` to `stdout`
  * [x] `read json <filename or data>`
    * [x] pre-parsed data, as file or string, is loaded and sets/replaces state
    * [ ] writes `"{\"ok\": true}"` or `"{\"errors\": [ ...]}"` to `stdout`
  * [x] `query <jq query string>`
    * [x] operates on state
    * [ ] writes `"{\"ok\": <result data>}"` or `"{\"errors\": [ ...]}"` to `stdout`
* [x] Testing
  * [x] Humans can use interactively
  * [x] #22

Tasks:
* [x] #15
* [x] #16
* [x] Refactor example code for reusability
* [x] Add `echo <msg>` command
* [x] #17
* [x] Add a shell banner and welcome message
* [x] Implement `read md`
* [x] Implement `read json`
* [x] Implement `query <jq query string>`

Backlogged:

* [x] #18

**Comment by oubiwann** [comment]
I think Rust's `clap` supports shell-building?

**Comment by oubiwann** [comment]
Yeah:
* https://github.com/clap-rs/clap/blob/master/examples/repl.rs

**Comment by oubiwann** [comment]
Done!
