### ISSUE TITLE
Create the tool

### ISSUE THREAD

**Issue by oubiwann** [oxur/mdsplode#2]
Based upon the need here:
* https://github.com/lfex/poise/issues/11

Tasks/features:
* [x] Set up project, CI/CD, logo, etc.
* [x] Publish placeholder (v0.0) on crates.io
* [x] #3
* [x] Pull together logic
* [x] Add clap for CLI support
* [x] #4
* [x] Output to stdout by default
* [x] #5
* [x] Support single file 'sploding
* [x] #6

**Comment by oubiwann** [comment]
Moving the rest to the next version.
