### ISSUE TITLE
Support multiple daemon modes

### ISSUE THREAD

**Issue by oubiwann** [oxur/mdsplode#29]
Features and tasks:
* [x] Add new CLI options
* [x] Refactor code to support different daemon modes
* [ ] Raw Erlang term support
* [ ] RPC mode (server) / Erlang distribution mode
* [ ] Document each
* [ ] Add "Daemon" section to README, with notes about modes (and links to example use in docs)

**Comment by oubiwann** [comment]
The following Rust libraries may be useful for this:
* https://docs.rs/eetf/latest/eetf/
* https://docs.rs/erl_dist/latest/erl_dist/
* https://docs.rs/erl_rpc/latest/erl_rpc/
